### ISSUE TITLE
Example HIT is too hard

### ISSUE THREAD

**Issue by ghost** [jcjohnson/simple-amt#9]
500-way classification of an object occluded by a grey box is just really tough, esp. when I'm only earning $0.03 of my own money :(.

**Comment by jcjohnson** [comment]
Sorry =(

**Comment by ghost** [comment]
I started trying this again today and somehow I got a much easier "describe this image with a sentence" HIT, so somehow the problem has been fixed. But yeah, last time I tried the tool I spent 10 minutes clicking all the 500 options and trying to guess that the countertop held a toaster.
